version: "3"

services:
  web:
    container_name: "ecommerce_app"
    build: .
    ports:
      - "80:80"
      - "8080:80"
      - "443:443"
    networks:
      ecommerce_network:
        ipv4_address: 192.168.151.51
    volumes:
      - .:/var/www/html
    tty: true
    stdin_open: true
    depends_on:
      - database

  database:
    image: mariadb:10.2.25-bionic
    container_name: "ecommerce_db"
    ports:
      - "3306:3306"
    networks:
      ecommerce_network:
        ipv4_address: 192.168.151.50
    volumes:
      - ./.docker/mariadb/data:/var/lib/mariadb
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: 123
    command: --default-authentication-plugin=mysql_native_password

networks:
  ecommerce_network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.151.0/24